/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as CheckoutReturnRouteImport } from './routes/checkout-return'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ResourcesWouldYouRatherRouteImport } from './routes/resources.would-you-rather'
import { Route as ResourcesNeverHaveIEverRouteImport } from './routes/resources.never-have-i-ever'
import { Route as ResourcesCheckInQuestionsRouteImport } from './routes/resources.check-in-questions'
import { Route as Resources36QuestionsRouteImport } from './routes/resources.36-questions'
import { Route as JoinCodeRouteImport } from './routes/join.$code'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPremiumRouteImport } from './routes/_authenticated/premium'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDailyRouteImport } from './routes/_authenticated/daily'
import { Route as AuthenticatedAtlasRouteImport } from './routes/_authenticated/atlas'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedQuestsIndexRouteImport } from './routes/_authenticated/quests.index'
import { Route as AuthenticatedCapsuleIndexRouteImport } from './routes/_authenticated/capsule.index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedQuestsChapterRouteImport } from './routes/_authenticated/quests.$chapter'
import { Route as AuthenticatedCapsuleNewRouteImport } from './routes/_authenticated/capsule.new'
import { Route as AuthenticatedCapsuleIdRouteImport } from './routes/_authenticated/capsule.$id'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout-return',
  path: '/checkout-return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesWouldYouRatherRoute = ResourcesWouldYouRatherRouteImport.update({
  id: '/resources/would-you-rather',
  path: '/resources/would-you-rather',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesNeverHaveIEverRoute = ResourcesNeverHaveIEverRouteImport.update({
  id: '/resources/never-have-i-ever',
  path: '/resources/never-have-i-ever',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesCheckInQuestionsRoute =
  ResourcesCheckInQuestionsRouteImport.update({
    id: '/resources/check-in-questions',
    path: '/resources/check-in-questions',
    getParentRoute: () => rootRouteImport,
  } as any)
const Resources36QuestionsRoute = Resources36QuestionsRouteImport.update({
  id: '/resources/36-questions',
  path: '/resources/36-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinCodeRoute = JoinCodeRouteImport.update({
  id: '/join/$code',
  path: '/join/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/confirm',
  path: '/confirm',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPremiumRoute = AuthenticatedPremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyRoute = AuthenticatedDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtlasRoute = AuthenticatedAtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedQuestsIndexRoute =
  AuthenticatedQuestsIndexRouteImport.update({
    id: '/quests/',
    path: '/quests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCapsuleIndexRoute =
  AuthenticatedCapsuleIndexRouteImport.update({
    id: '/capsule/',
    path: '/capsule/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedQuestsChapterRoute =
  AuthenticatedQuestsChapterRouteImport.update({
    id: '/quests/$chapter',
    path: '/quests/$chapter',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCapsuleNewRoute = AuthenticatedCapsuleNewRouteImport.update({
  id: '/capsule/new',
  path: '/capsule/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCapsuleIdRoute = AuthenticatedCapsuleIdRouteImport.update({
  id: '/capsule/$id',
  path: '/capsule/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/checkout-return': typeof CheckoutReturnRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atlas': typeof AuthenticatedAtlasRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/home': typeof AuthenticatedHomeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/join/$code': typeof JoinCodeRoute
  '/resources/36-questions': typeof Resources36QuestionsRoute
  '/resources/check-in-questions': typeof ResourcesCheckInQuestionsRoute
  '/resources/never-have-i-ever': typeof ResourcesNeverHaveIEverRoute
  '/resources/would-you-rather': typeof ResourcesWouldYouRatherRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/capsule/$id': typeof AuthenticatedCapsuleIdRoute
  '/capsule/new': typeof AuthenticatedCapsuleNewRoute
  '/quests/$chapter': typeof AuthenticatedQuestsChapterRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/capsule/': typeof AuthenticatedCapsuleIndexRoute
  '/quests/': typeof AuthenticatedQuestsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/checkout-return': typeof CheckoutReturnRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atlas': typeof AuthenticatedAtlasRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/home': typeof AuthenticatedHomeRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/premium': typeof AuthenticatedPremiumRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/join/$code': typeof JoinCodeRoute
  '/resources/36-questions': typeof Resources36QuestionsRoute
  '/resources/check-in-questions': typeof ResourcesCheckInQuestionsRoute
  '/resources/never-have-i-ever': typeof ResourcesNeverHaveIEverRoute
  '/resources/would-you-rather': typeof ResourcesWouldYouRatherRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/capsule/$id': typeof AuthenticatedCapsuleIdRoute
  '/capsule/new': typeof AuthenticatedCapsuleNewRoute
  '/quests/$chapter': typeof AuthenticatedQuestsChapterRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/capsule': typeof AuthenticatedCapsuleIndexRoute
  '/quests': typeof AuthenticatedQuestsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/checkout-return': typeof CheckoutReturnRoute
  '/mcp': typeof McpRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/atlas': typeof AuthenticatedAtlasRoute
  '/_authenticated/daily': typeof AuthenticatedDailyRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/premium': typeof AuthenticatedPremiumRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/join/$code': typeof JoinCodeRoute
  '/resources/36-questions': typeof Resources36QuestionsRoute
  '/resources/check-in-questions': typeof ResourcesCheckInQuestionsRoute
  '/resources/never-have-i-ever': typeof ResourcesNeverHaveIEverRoute
  '/resources/would-you-rather': typeof ResourcesWouldYouRatherRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/capsule/$id': typeof AuthenticatedCapsuleIdRoute
  '/_authenticated/capsule/new': typeof AuthenticatedCapsuleNewRoute
  '/_authenticated/quests/$chapter': typeof AuthenticatedQuestsChapterRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_authenticated/capsule/': typeof AuthenticatedCapsuleIndexRoute
  '/_authenticated/quests/': typeof AuthenticatedQuestsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout-return'
    | '/mcp'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/atlas'
    | '/daily'
    | '/home'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/auth/confirm'
    | '/join/$code'
    | '/resources/36-questions'
    | '/resources/check-in-questions'
    | '/resources/never-have-i-ever'
    | '/resources/would-you-rather'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/capsule/$id'
    | '/capsule/new'
    | '/quests/$chapter'
    | '/api/public/health'
    | '/capsule/'
    | '/quests/'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/checkout-return'
    | '/mcp'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/atlas'
    | '/daily'
    | '/home'
    | '/onboarding'
    | '/premium'
    | '/profile'
    | '/auth/confirm'
    | '/join/$code'
    | '/resources/36-questions'
    | '/resources/check-in-questions'
    | '/resources/never-have-i-ever'
    | '/resources/would-you-rather'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/capsule/$id'
    | '/capsule/new'
    | '/quests/$chapter'
    | '/api/public/health'
    | '/capsule'
    | '/quests'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/checkout-return'
    | '/mcp'
    | '/privacy'
    | '/security'
    | '/sitemap.xml'
    | '/terms'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/atlas'
    | '/_authenticated/daily'
    | '/_authenticated/home'
    | '/_authenticated/onboarding'
    | '/_authenticated/premium'
    | '/_authenticated/profile'
    | '/auth/confirm'
    | '/join/$code'
    | '/resources/36-questions'
    | '/resources/check-in-questions'
    | '/resources/never-have-i-ever'
    | '/resources/would-you-rather'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/capsule/$id'
    | '/_authenticated/capsule/new'
    | '/_authenticated/quests/$chapter'
    | '/api/public/health'
    | '/_authenticated/capsule/'
    | '/_authenticated/quests/'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  McpRoute: typeof McpRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  JoinCodeRoute: typeof JoinCodeRoute
  Resources36QuestionsRoute: typeof Resources36QuestionsRoute
  ResourcesCheckInQuestionsRoute: typeof ResourcesCheckInQuestionsRoute
  ResourcesNeverHaveIEverRoute: typeof ResourcesNeverHaveIEverRoute
  ResourcesWouldYouRatherRoute: typeof ResourcesWouldYouRatherRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-return': {
      id: '/checkout-return'
      path: '/checkout-return'
      fullPath: '/checkout-return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/would-you-rather': {
      id: '/resources/would-you-rather'
      path: '/resources/would-you-rather'
      fullPath: '/resources/would-you-rather'
      preLoaderRoute: typeof ResourcesWouldYouRatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/never-have-i-ever': {
      id: '/resources/never-have-i-ever'
      path: '/resources/never-have-i-ever'
      fullPath: '/resources/never-have-i-ever'
      preLoaderRoute: typeof ResourcesNeverHaveIEverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/check-in-questions': {
      id: '/resources/check-in-questions'
      path: '/resources/check-in-questions'
      fullPath: '/resources/check-in-questions'
      preLoaderRoute: typeof ResourcesCheckInQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/36-questions': {
      id: '/resources/36-questions'
      path: '/resources/36-questions'
      fullPath: '/resources/36-questions'
      preLoaderRoute: typeof Resources36QuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$code': {
      id: '/join/$code'
      path: '/join/$code'
      fullPath: '/join/$code'
      preLoaderRoute: typeof JoinCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/premium': {
      id: '/_authenticated/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof AuthenticatedPremiumRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily': {
      id: '/_authenticated/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof AuthenticatedDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atlas': {
      id: '/_authenticated/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AuthenticatedAtlasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quests/': {
      id: '/_authenticated/quests/'
      path: '/quests'
      fullPath: '/quests/'
      preLoaderRoute: typeof AuthenticatedQuestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capsule/': {
      id: '/_authenticated/capsule/'
      path: '/capsule'
      fullPath: '/capsule/'
      preLoaderRoute: typeof AuthenticatedCapsuleIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/quests/$chapter': {
      id: '/_authenticated/quests/$chapter'
      path: '/quests/$chapter'
      fullPath: '/quests/$chapter'
      preLoaderRoute: typeof AuthenticatedQuestsChapterRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capsule/new': {
      id: '/_authenticated/capsule/new'
      path: '/capsule/new'
      fullPath: '/capsule/new'
      preLoaderRoute: typeof AuthenticatedCapsuleNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/capsule/$id': {
      id: '/_authenticated/capsule/$id'
      path: '/capsule/$id'
      fullPath: '/capsule/$id'
      preLoaderRoute: typeof AuthenticatedCapsuleIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAtlasRoute: typeof AuthenticatedAtlasRoute
  AuthenticatedDailyRoute: typeof AuthenticatedDailyRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPremiumRoute: typeof AuthenticatedPremiumRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedCapsuleIdRoute: typeof AuthenticatedCapsuleIdRoute
  AuthenticatedCapsuleNewRoute: typeof AuthenticatedCapsuleNewRoute
  AuthenticatedQuestsChapterRoute: typeof AuthenticatedQuestsChapterRoute
  AuthenticatedCapsuleIndexRoute: typeof AuthenticatedCapsuleIndexRoute
  AuthenticatedQuestsIndexRoute: typeof AuthenticatedQuestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAtlasRoute: AuthenticatedAtlasRoute,
  AuthenticatedDailyRoute: AuthenticatedDailyRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPremiumRoute: AuthenticatedPremiumRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedCapsuleIdRoute: AuthenticatedCapsuleIdRoute,
  AuthenticatedCapsuleNewRoute: AuthenticatedCapsuleNewRoute,
  AuthenticatedQuestsChapterRoute: AuthenticatedQuestsChapterRoute,
  AuthenticatedCapsuleIndexRoute: AuthenticatedCapsuleIndexRoute,
  AuthenticatedQuestsIndexRoute: AuthenticatedQuestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AuthRouteChildren {
  AuthConfirmRoute: typeof AuthConfirmRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthConfirmRoute: AuthConfirmRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  CheckoutReturnRoute: CheckoutReturnRoute,
  McpRoute: McpRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  JoinCodeRoute: JoinCodeRoute,
  Resources36QuestionsRoute: Resources36QuestionsRoute,
  ResourcesCheckInQuestionsRoute: ResourcesCheckInQuestionsRoute,
  ResourcesNeverHaveIEverRoute: ResourcesNeverHaveIEverRoute,
  ResourcesWouldYouRatherRoute: ResourcesWouldYouRatherRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
